### ISSUE TITLE
Conexão recusada

### ISSUE THREAD

**Issue by krismorte** [uliss3s/ceputil#4]
Estou tetando passar pelo proxy, mas estou recebendo conexão recusada

```
 System.setProperty("http.proxyHost", "");
        System.setProperty("http.proxyPort", "");
        System.setProperty("https.proxyHost", "");
        System.setProperty("https.proxyPort", "");

```
```
--- exec-maven-plugin:1.2.1:exec (default-cli) @ correios.br ---
Exception in thread "main" java.lang.RuntimeException: org.apache.http.conn.HttpHostConnectException: Connection to https://viacep.com.br refused
	at com.krismorte.correios.br.ws.CorreiosService.sendRequest(CorreiosService.java:82)
	at com.krismorte.correios.br.logradouro.BuscaEndereco.getEnderecoPorCep(BuscaEndereco.java:59)
	at Teste.testeBuscaCep(Teste.java:44)
	at Teste.main(Teste.java:59)
Caused by: org.apache.http.conn.HttpHostConnectException: Connection to https://viacep.com.br refused
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:190)
	at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:294)
	at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:645)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:480)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:906)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:805)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:784)
	at com.krismorte.correios.br.ws.CorreiosService.sendRequest(CorreiosService.java:75)
```

**Comment by uliss3s** [comment]
Você conseguiu resolver?

Eu testei e não consegui reproduzir o problema.

Caso não tenha resolvido, por favor postar o código completo da classe para que eu faço o teste.

**Comment by lucazin** [comment]
Essa API pega direto do correios? 
Como usar a api pra pegar dados direto do correios ?
